In [2]:
# Useful starting lines
%matplotlib inline

import numpy as np
import scipy
import scipy.io
import scipy.sparse as sp
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

In [2]:
import csv
with open("data/tmp.csv","r") as f:
    reader = csv.reader(f,delimiter = ",")
    data = list(reader)
    row_count = len(data)

In [3]:
row_count

1176953

In [19]:
ar = sp.lil_matrix([[2,0,4,0,0,4],[2,0,3,0,6,0],[10,4,7,0,0,6],[2,0,8,2,0,0],[2,0,4,0,0,4],[2,0,3,0,6,0],[10,4,7,0,0,6],[2,0,8,2,0,0]])
ar.todense()

matrix([[ 2,  0,  4,  0,  0,  4],
        [ 2,  0,  3,  0,  6,  0],
        [10,  4,  7,  0,  0,  6],
        [ 2,  0,  8,  2,  0,  0],
        [ 2,  0,  4,  0,  0,  4],
        [ 2,  0,  3,  0,  6,  0],
        [10,  4,  7,  0,  0,  6],
        [ 2,  0,  8,  2,  0,  0]], dtype=int64)

In [24]:
row_,col_ = ar[:,1].nonzero()

(array([2, 6], dtype=int32), array([0, 0], dtype=int32))

In [6]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity = pairwise_distances(ar, metric='cosine')
#item_similarity = pairwise_distances(train_data_matrix.T, metric='cosine')

In [18]:
user_similarity

array([[ 0.        ,  0.00772212,  0.63726187,  0.0513167 ],
       [ 0.00772212,  0.        ,  0.55007873,  0.01941932],
       [ 0.63726187,  0.55007873,  0.        ,  0.42646067],
       [ 0.0513167 ,  0.01941932,  0.42646067,  0.        ]])

In [28]:
ar.shape[1]

6

In [25]:
nz_row, nz_col = ar.nonzero()
nz_train = list(zip(nz_row, nz_col))
#print(nz_train)
for i in range(ar.shape[1]):
    sub_mat = 

0
2
5
0
2
4
0
1
2
5
0
2
3
0
2
5
0
2
4
0
1
2
5
0
2
3


In [9]:
a_small = sp.lil_matrix([[2,0,4,0,0],[3,0,5,0,2],[1,0,0,0,6],[7,4,8,0,0]])
a_small.todense()

matrix([[2, 0, 4, 0, 0],
        [3, 0, 5, 0, 2],
        [1, 0, 0, 0, 6],
        [7, 4, 8, 0, 0]], dtype=int64)

In [11]:
b = pairwise_distances(a_small, metric='cosine')
b

array([[ 0.        ,  0.05688087,  0.92647854,  0.09437588],
       [ 0.05688087,  0.        ,  0.59996444,  0.12874922],
       [ 0.92647854,  0.59996444,  0.        ,  0.89867833],
       [ 0.09437588,  0.12874922,  0.89867833,  0.        ]])

In [44]:
a_array = np.array([[2,0,4,0,0,1],[10,0,4,5,0,1],[1,0,0,0,6,1],[7,4,8,0,0,1],[2,0,4,0,0,1]])
a_array

array([[ 2,  0,  4,  0,  0,  1],
       [10,  0,  4,  5,  0,  1],
       [ 1,  0,  0,  0,  6,  1],
       [ 7,  4,  8,  0,  0,  1],
       [ 2,  0,  4,  0,  0,  1]])

In [42]:
c = pairwise_distances(a_array, metric='cosine')
c

array([[ 0.        ,  0.32243977,  0.89380115,  0.10046817,  0.        ],
       [ 0.32243977,  0.        ,  0.85025349,  0.24190894,  0.32243977],
       [ 0.89380115,  0.85025349,  0.        ,  0.88617792,  0.89380115],
       [ 0.10046817,  0.24190894,  0.88617792,  0.        ,  0.10046817],
       [ 0.        ,  0.32243977,  0.89380115,  0.10046817,  0.        ]])

In [ ]:
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.evaluation import BinaryClassificationEvaluator
from pyspark.ml.linalg import Vectors
dataset = spark.createDataFrame(
    [(Vectors.dense([0.0]), 0.0),
     (Vectors.dense([0.4]), 1.0),
     (Vectors.dense([0.5]), 0.0),
     (Vectors.dense([0.6]), 1.0),
     (Vectors.dense([1.0]), 1.0)] * 10,
    ["features", "label"])
lr = LogisticRegression()
grid = ParamGridBuilder().addGrid(lr.maxIter, [0, 1]).build()
evaluator = BinaryClassificationEvaluator()
cv = CrossValidator(estimator=lr, estimatorParamMaps=grid, evaluator=evaluator)
cvModel = cv.fit(dataset)
evaluator.evaluate(cvModel.transform(dataset))

In [6]:
from pyspark.sql import SparkSession

spark = SparkSession\
        .builder\
        .appName("ALSExample")\
        .getOrCreate()


from pyspark.ml.linalg import Vectors
dataset = spark.createDataFrame(
    [(Vectors.dense([0.0]), 0.0),
     (Vectors.dense([0.4]), 1.0),
     (Vectors.dense([0.5]), 0.0),
     (Vectors.dense([0.6]), 1.0),
     (Vectors.dense([1.0]), 1.0)] * 10,
    ["features", "label"])

In [15]:
from pyspark.ml.classification import LogisticRegression
lr = LogisticRegression()

In [17]:
from pyspark.ml.tuning import ParamGridBuilder
grid = ParamGridBuilder().addGrid(lr.maxIter, [0, 1]).build()

In [19]:
from pyspark.ml.evaluation import BinaryClassificationEvaluator
evaluator = BinaryClassificationEvaluator()

In [24]:
from pyspark.ml.tuning import CrossValidator
cv = CrossValidator(estimator=lr, estimatorParamMaps=grid, evaluator=evaluator)
cvModel = cv.fit(dataset)

In [28]:
grid

[{Param(parent='LogisticRegression_429eacf663efbef26ffe', name='maxIter', doc='max number of iterations (>= 0).'): 0},
 {Param(parent='LogisticRegression_429eacf663efbef26ffe', name='maxIter', doc='max number of iterations (>= 0).'): 1}]

In [27]:
evaluator.evaluate(cvModel.transform(dataset))

0.8333333333333333

In [3]:
ar = sp.lil_matrix([[2,0,4,0,0,4],[2,0,3,0,6,0],[10,4,7,0,0,6],[2,0,8,2,0,0],[2,0,4,0,0,4],[2,0,3,0,6,0],[10,4,7,0,0,6],[2,0,8,2,0,0]])
ar.todense()

matrix([[ 2,  0,  4,  0,  0,  4],
        [ 2,  0,  3,  0,  6,  0],
        [10,  4,  7,  0,  0,  6],
        [ 2,  0,  8,  2,  0,  0],
        [ 2,  0,  4,  0,  0,  4],
        [ 2,  0,  3,  0,  6,  0],
        [10,  4,  7,  0,  0,  6],
        [ 2,  0,  8,  2,  0,  0]], dtype=int64)

In [6]:
from scipy.sparse.linalg import svds

#get SVD components from train matrix. Choose k.
u, s, vt = svds(ar, k = 4)
#s_diag_matrix=np.diag(s)
#X_pred = np.dot(np.dot(u, s_diag_matrix), vt)
#print 'User-based CF MSE: ' + str(rmse(X_pred, test_data_matrix))

ValueError: matrix type must be 'f', 'd', 'F', or 'D'

In [ ]:
    >>> from pyspark.ml.classification import LogisticRegression
    >>> lr = LogisticRegression()
    
    >>> output = ParamGridBuilder() \
    ...     .baseOn({lr.labelCol: 'l'}) \
    ...     .baseOn([lr.predictionCol, 'p']) \
    ...     .addGrid(lr.regParam, [1.0, 2.0]) \
    ...     .addGrid(lr.maxIter, [1, 5]) \
    ...     .build()
    
    >>> expected = [
    ...     {lr.regParam: 1.0, lr.maxIter: 1, lr.labelCol: 'l', lr.predictionCol: 'p'},
    ...     {lr.regParam: 2.0, lr.maxIter: 1, lr.labelCol: 'l', lr.predictionCol: 'p'},
    ...     {lr.regParam: 1.0, lr.maxIter: 5, lr.labelCol: 'l', lr.predictionCol: 'p'},
    ...     {lr.regParam: 2.0, lr.maxIter: 5, lr.labelCol: 'l', lr.predictionCol: 'p'}]
    
    >>> len(output) == len(expected)
    True
    >>> all([m in expected for m in output])
    True

In [29]:
from pyspark.ml.classification import LogisticRegression
lr = LogisticRegression()
output = ParamGridBuilder() \
    .baseOn({lr.labelCol: 'l'}) \
    .baseOn([lr.predictionCol, 'p']) \
    .addGrid(lr.regParam, [1.0, 2.0]) \
    .addGrid(lr.maxIter, [1, 5]) \
    .build()

In [30]:
output

[{Param(parent='LogisticRegression_487881b0cfb8e88c13c2', name='labelCol', doc='label column name.'): 'l',
  Param(parent='LogisticRegression_487881b0cfb8e88c13c2', name='regParam', doc='regularization parameter (>= 0).'): 1.0,
  Param(parent='LogisticRegression_487881b0cfb8e88c13c2', name='maxIter', doc='max number of iterations (>= 0).'): 1,
  Param(parent='LogisticRegression_487881b0cfb8e88c13c2', name='predictionCol', doc='prediction column name.'): 'p'},
 {Param(parent='LogisticRegression_487881b0cfb8e88c13c2', name='labelCol', doc='label column name.'): 'l',
  Param(parent='LogisticRegression_487881b0cfb8e88c13c2', name='regParam', doc='regularization parameter (>= 0).'): 1.0,
  Param(parent='LogisticRegression_487881b0cfb8e88c13c2', name='maxIter', doc='max number of iterations (>= 0).'): 5,
  Param(parent='LogisticRegression_487881b0cfb8e88c13c2', name='predictionCol', doc='prediction column name.'): 'p'},
 {Param(parent='LogisticRegression_487881b0cfb8e88c13c2', name='labelCol